title: Cloud Native Observability
description: Learn to gain visibility into distributed systems by combining tracing, metrics and logging with OpenTelemetry.
site_title: "Cloud Native Observability"

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: codeboten
blog_url: https://words.boten.ca
email:
twitter_username: codeboten

# absolute or relative
profile_picture: /assets/images/telescope.png

# Google Analytics ID
google_analytics:
