title: Cloud Native Observability
description: Web & Security Engineer
site_title: "Cloud Native Observability"

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: codeboten
blog_url: https://words.boten.ca
email:
twitter_username: codeboten

# absolute or relative
profile_picture:

# Google Analytics ID
google_analytics:
